### ISSUE TITLE
Tries to Read from a Write descriptor, hangs

### ISSUE THREAD

**Issue by bwesen** [NordicSemiconductor/IOS-nRF-Connect#41] opened 2018-09-26 14:36 UTC
Hi, I have an u-Blox BLE module I'm developing on (it uses the nrf chips), I'm setting up a custom service ff00 with a custom Read/Notify characteristic ff01 and a Write characteristic ff02 on it.

From the Android version of nRF Connect, everything works as intended.

On the iOS version, as soon as I click on the Service, it seems it tries to READ from the ff02 Write-only characteristic, because I get an unsolicited Read note on the BLE module (it has a built-in ublox connectivity software with AT commands and stuff).

Then the nRF Connect app times out after a while and disconnects.

Bug in the app or in the BLE module?

Bug in my brain? (do you always need a READ permission on characteristic that are going to be used for WRITE only?)

**Comment by philips77** [comment] 2018-09-26 14:44
Your uBox should respond with an error that the desc is write-only (afair). nRF Connect can't know if a descriptor support read or write or both. There are no properties for descriptors.

**Comment by bwesen** [comment] 2018-09-26 14:50
> Your uBox should respond with an error that the desc is write-only (afair). nRF Connect can't know if a descriptor support read or write or both. There are no properties for descriptors.

It shows the properties (READ, WRITE, WRITE RESPONSE, NOTIFY) for each characteristic in the service (my terminology was bugged above maybe, I meant characteristics when I wrote descriptors - I really hate the nomenclature in BLE :).

I installed the BlueSee iOS app instead and that works as intended (doesn't try to read from all descriptors and I can read, notify and write to the descriptors in the service).

I don't think the u-blox software is bug-free, far from it, but it just seems the nrf app also could avoid doing these reads in the first place :)

**Comment by philips77** [comment] 2018-09-26 14:58
Well... I've fixed your comments :)
So yes, nRF Connect shouldn't read from characteristics without Read property, at least not automatically. That's a big on our side, @mostafaberg. But still, i think that the device should respond with some error. It perhaps it does, but nRF just waits for a valid response?

**Comment by mostafaberg** [comment] 2018-10-09 09:29
Strange that it Hangs indeed, this shouldn't be happening, are you stil having the issue or did you manage to resolve it ?

**Comment by bwesen** [comment] 2018-10-09 09:39
I got my iOS custom code working, to access my device with, which worked fine for both read and write to my custom service and characteristics, so I didn't really try the nRF Connect app again in this case.

I think the problem was that the nRF Connect app tries to read from the write characteristic, and then the u-blox firmware for some reason doesn't reject this but instead asks the local MCU for data (the BLE module in this case is connected to the MCU by a serial port doing AT-style commands, and when a read comes in on a characteristic without a value set, it does an unsolicited AT response to ask the MCU for the value). I don't know enough about BLE link-level handshakes to say anything about if it's even possible for a BLE Peripheral to actually allow a read from a char without the read property but it seems like it :) 

So maybe a combination of two bugs :)

**Comment by mostafaberg** [comment] 2018-10-09 09:42
Yeah I understand, most important is that you have things working now, it's most probably a bug on the firmware side since reading from a write only characteristic never hangs any of the chips we worked on :)

closing this for now and if you encounter any issues just reopen or create a new ticket and we'll gladly help 👍

**Comment by bwesen** [comment] 2018-10-09 10:39
To be fair, it didn't hang the chip, it hung the nRF Connect app. The BLE module kept working fine all the time.

**Comment by mostafaberg** [comment] 2018-10-09 10:40
oh I see, I think I misunderstood your bug report then!, did it crash the app or fully hang ?

**Comment by bwesen** [comment] 2018-10-09 10:41
It hung the app, probably because it was waiting for a reply on the read, which the BLE module didn't provide (as I didn't tell it to due to it being a write-only characteristic). I guess it's a matter of definitions, what is supposed to happen in that case I mean :)

**Comment by mostafaberg** [comment] 2018-10-09 10:42
hmmm ok, I'll leave the issue open and try to reproduce and see if I can, then I'll post my findings later on ! thanks again for the feedback, most importantly you got your part working 👍

**Closed** 2020-07-29 08:02 UTC
