### ISSUE TITLE
updated IOS nRF connect app does not show the expected returning data from firmware, see screenshot for details

### ISSUE THREAD

**Issue by xingguo-huang2** [NordicSemiconductor/IOS-nRF-Connect#145] opened 2024-01-05 20:19 UTC
I was using nRF connect IOS version just fine, but someday a few week ago, since I updated the app on my iphone, then the app stopped working as expected(no return data from firmware can be observed on the app). 

I happened to have an older version of the **iPad** IOS nRF app which works fine. 

However, when I try to use my updated **iPhone** app to communicate with the firmware, it won't show me the returned data.

![IMG_2AAB59A5E147-1](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/137120956/e0d37d49-0775-496d-aeec-714b0f52015f)
![IMG_2284](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/137120956/98af8db1-1797-47c3-a3df-bd4d48a39f30)

**Comment by dinesharjani** [comment] 2024-01-08 12:17
Oh, that's a good one. So what's happening is that the 'write' is not triggering a Log update, but the Write is happening as you can see from 'Client' tab. It's a fault caused by optimising the Logs screen to not update in the background when you can't see the logs, only it's not updating when you return to them.

**Comment by dinesharjani** [comment] 2024-01-08 12:27
Marking this as fixed. Will ship with version 2.7.3.

**Closed by dinesharjani** 2024-01-08 12:27 UTC
Labels: reproduces, bug

**Comment by xingguo-huang2** [comment] 2024-01-26 20:16
> Marking this as fixed. Will ship with version 2.7.3.

Upgraded to 2.7.5, the problem is still not fixed.....

![IMG_0364](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/137120956/8fafa29c-daa6-49fb-a47e-e58a312ddcd0)
![IMG_0365](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/137120956/31d5fcb3-310a-457b-8a7c-b678ed6e7010)

**Comment by xingguo-huang2** [comment] 2024-01-26 20:18
Please help fix the above issue... Thank you!

**Comment by philips77** [comment] 2024-01-26 20:23
Based on the image from the first comment you're disabling notifications just after enabling them:
![294601104-98af8db1-1797-47c3-a3df-bd4d48a39f30](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/cbf7cf7e-4a0c-41d9-8129-cbfa674a6142)

When disabled, you'll not get any updates.

**Comment by xingguo-huang2** [comment] 2024-01-26 21:31
![Screenshot 2024-01-26 at 1 29 29 PM](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/137120956/e7ff4b97-1d3e-4685-8150-55273eb80f8e)
Thank you very much! This worked for me. Just post it here in case someone will need it.
