### ISSUE TITLE
Button for "Write request" in a BLE service not responding

### ISSUE THREAD

**Issue by carljohanlandin** [NordicSemiconductor/IOS-nRF-Connect#147] opened 2024-02-20 12:35 UTC
I have a BLE application based on the peripheral_lbs sample running on a nrf52840dk. I have previously been able to use the iOS nrf connect app to send write requests to my device but after the app has been updated the write button in the BLE service is unresponsive.

I have confirmed that the problem is not in my application by using nrf connect desktop, from which it works sending the same write requests.

**Comment by dinesharjani** [comment] 2024-02-20 12:51
I will make a fresh peripheral_lbs sample and run it on an nrf52840dk - thanks for specifying that info.

But, if you move over to Logs, can you see the write requests happening? Remember to enable all Debug Log Levels to check for this.

**Comment by carljohanlandin** [comment] 2024-02-20 14:02
Hi Dinesh, Thanks for looking into it.

I have enabled the debug log level as well but still can’t see any log
events related to writing after pushing the write button.

Best regards
Carl-Johan


tis 20 feb. 2024 kl. 13:52 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-20 14:03
Which iPhone are we talking about?

**Comment by carljohanlandin** [comment] 2024-02-20 14:04
iPhone 12 Pro


tis 20 feb. 2024 kl. 15:04 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-20 14:08
May I see a screenshot? Perhaps this allows me to have a better idea of what the issue might be. A screenshot of Device Details (Client), I assume this is where the issue is.

**Comment by dinesharjani** [comment] 2024-02-20 14:18
Unfortunately I can't see the screenshot. Neither via email nor GitHub comments :(

You may cover up the names / UUIDs of Services and so on. I just need to get a general idea of the state of the UI, and see the Buttons and in which cells / attributes they're visible / usable from.

**Comment by carljohanlandin** [comment] 2024-02-20 14:23
![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/40301341/b6d94d6b-6d4f-4451-9ff8-ae1fcec7468c)

Hope this works better

**Comment by dinesharjani** [comment] 2024-02-20 14:27
Definitely better but unfortunately I cant see the buttons which are on the right side of the screen.

**Comment by carljohanlandin** [comment] 2024-02-20 14:27
I realised I accidentally cropped the picture. Here it is again

![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/40301341/8d4cb927-a27e-47ff-a1f3-a7fbc58cc351)

**Comment by dinesharjani** [comment] 2024-02-20 14:29
I see. I will do some testing tomorrow. But this screenshot is helpful - thank you.

**Comment by carljohanlandin** [comment] 2024-02-20 14:30
Great, thanks for the help.

Best regards
Carl-Johan


tis 20 feb. 2024 kl. 15:29 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-21 10:29
When you tap the Write button (arrow pointing up), do you get the Write Characteristic Dialog? And you can type in Data and then tap 'Write' ?

**Comment by carljohanlandin** [comment] 2024-02-21 10:31
No, nothing happens. No dialog appears.

ons 21 feb. 2024 kl. 11:29 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-21 10:41
If you try to Write another Characteristic / another Device etc, does it work? Is it only for the particular Attribute / firmware you're writing or is it in general the Write Dialog doesn't show up for anything?

**Comment by carljohanlandin** [comment] 2024-02-21 12:07
Just now I tried to flash the actual peripheral_lbs sample (instead of my
own app built from it) and the same issue remains. However, I can interact
with the read buttons. Enabling notifications for when the button is
pressed and released works. Also reading the client charecteristic
configuration attribute works. But both the “Blinky LED state” write button
and the “Client characteristic configuration” write button is not
responding. I can only see those buttons changing color as I hold my finger
on them. But that’s it.


ons 21 feb. 2024 kl. 11:41 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-21 12:12
Ok, I believe I see the issue. It's related to the Write Type, which looks like it's registered as 'Authenticated Signed Write'. I managed to cause it and reproduce it in the current version out in the App Store - Write Button is there but nothing happens no matter how much I tap it.

Can I send you a TestFlight beta link with a possible fix to your email address ?

**Comment by carljohanlandin** [comment] 2024-02-21 12:16
Good catch:)

Sure, no problem.

ons 21 feb. 2024 kl. 13:12 skrev Dinesh Harjani ***@***.***>:

**Comment by dinesharjani** [comment] 2024-02-21 12:55
@carljohanlandin I cannot see your emaiil because GitHub is protecting it.

Please write me to dinesh.harjani@nordicsemi.no with the email address of your Apple ID (or the Apple ID of the device where you want to test this) so I can add you to TestFlight

**Comment by dinesharjani** [comment] 2024-02-22 10:35
Closing as this issue has been confirmed by @carljohanlandin as fixed for nRF Connect 2.7.6 (in Beta)

**Closed by dinesharjani** 2024-02-22 10:35 UTC
Labels: bug
